# Generated by Django 5.0.1 on 2024-08-05 09:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='', max_length=10, null=True)),
                ('religion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_images/default-profile-image.png', null=True, upload_to='profile_images/')),
                ('nationality', models.CharField(blank=True, default='Nigeria', max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, default='', max_length=20)),
                ('profile_url', models.CharField(blank=True, max_length=30, null=True)),
                ('otp_token', models.CharField(blank=True, max_length=5, null=True)),
                ('is_admin_user', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lecturer', models.BooleanField(default=False)),
                ('lecturer_rank', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_role', models.CharField(blank=True, max_length=20, null=True)),
                ('lecturer_availability', models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(blank=True, max_length=20, null=True)),
                ('level_year', models.IntegerField(blank=True, choices=[(1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four'), (5, 'Level Five')], null=True)),
                ('current_semester', models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester')], default=1, null=True)),
                ('current_cgpa', models.CharField(blank=True, max_length=10, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
