# Generated by Django 5.0.6 on 2024-07-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='country',
            new_name='nationality',
        ),
        migrations.AddField(
            model_name='account',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
