# Generated by Django 5.0.1 on 2024-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='is_lecturer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
        migrations.AddField(
            model_name='account',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
