# Generated by Django 5.0.6 on 2024-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_country_account_nationality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='lecturer_title',
            new_name='lecturer_rank',
        ),
        migrations.AlterField(
            model_name='account',
            name='active_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
