# Generated by Django 5.0.6 on 2024-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_is_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
