# Generated by Django 5.0.6 on 2024-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_current_semester_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
