# Generated by Django 5.0.6 on 2024-07-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_token',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
