# Generated by Django 5.0.6 on 2024-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_otp_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active_status',
        ),
        migrations.AddField(
            model_name='account',
            name='lecturer_availability',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_semester',
            field=models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='level_year',
            field=models.IntegerField(blank=True, choices=[(1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four'), (5, 'Level Five')], null=True),
        ),
    ]
