# Generated by Django 5.0.6 on 2024-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource',
            field=models.FileField(default=1, upload_to='resources/'),
            preserve_default=False,
        ),
    ]
