# Generated by Django 5.0.6 on 2024-07-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecturer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Lecturer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Availability_status', models.CharField(blank=True, choices=[('available', 'Available'), ('active', 'Active')], default='', max_length=255, null=True)),
                ('Course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Course_unit', models.IntegerField()),
                ('Lecture_day_and_time', models.DateTimeField()),
                ('Course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('Outstanding_courses', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
