# Generated by Django 5.0.6 on 2024-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courses_current_cgpa_courses_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Availability_status',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('Unavailable', 'Unavailable'), ('Pending', 'Pending'), ('completed', 'Completed')], default='Available', max_length=255, null=True),
        ),
    ]
