# Generated by Django 5.0.1 on 2024-08-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_lecturer_is_lecturer_and_more'),
        ('course', '0002_alter_courses_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstandingcourses',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
