# Generated by Django 5.0.6 on 2024-07-31 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_courses_availability_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Course_code',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Course_title',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Course_unit',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Lecture_day_and_time',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Lecturer_email',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Lecturer_name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Outstanding_courses',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_status',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='current_cgpa',
        ),
        migrations.AddField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='lecture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='lecture_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four'), (5, 'Level Five')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='OutstandingCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='outstanding_courses', to='course.courses')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
