# Generated by Django 5.0.6 on 2024-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_image', models.ImageField(blank=True, null=True, upload_to='rep_images/')),
                ('rank', models.CharField(blank=True, max_length=25, null=True)),
                ('academic_position', models.CharField(blank=True, max_length=20, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
