# Generated by Django 5.0.6 on 2024-08-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_remove_lecturer_is_lecturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('info_description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
                ('other_titles', models.CharField(blank=True, max_length=50, null=True)),
                ('reps_degree', models.CharField(blank=True, max_length=20, null=True)),
                ('reps_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.lecturer')),
            ],
        ),
    ]
