# Generated by Django 5.0.6 on 2024-08-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='reps_degree',
            new_name='academic_position',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='info_description',
            new_name='dept_description',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='other_titles',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='reps_name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='rank',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='rep_image',
            field=models.ImageField(blank=True, null=True, upload_to='rep_images/'),
        ),
    ]
