# Generated by Django 5.0.6 on 2024-08-07 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_rename_reps_degree_faculty_academic_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='date_posted',
            field=models.DateField(default=datetime.date(2024, 8, 7)),
        ),
    ]
