# Generated by Django 5.0.6 on 2024-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
