# Generated by Django 5.0.6 on 2024-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
